/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IConvexStakingWrapperFrax,
  IConvexStakingWrapperFraxInterface,
} from "../IConvexStakingWrapperFrax";

const _abi = [
  {
    inputs: [],
    name: "curveToken",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IConvexStakingWrapperFrax__factory {
  static readonly abi = _abi;
  static createInterface(): IConvexStakingWrapperFraxInterface {
    return new utils.Interface(_abi) as IConvexStakingWrapperFraxInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IConvexStakingWrapperFrax {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IConvexStakingWrapperFrax;
  }
}
