/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IEventSender, IEventSenderInterface } from "../IEventSender";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "fxStateSender",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "destinationOnL2",
        type: "address",
      },
    ],
    name: "DestinationsSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bool",
        name: "eventSendSet",
        type: "bool",
      },
    ],
    name: "EventSendSet",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "fxStateSender",
        type: "address",
      },
      {
        internalType: "address",
        name: "destinationOnL2",
        type: "address",
      },
    ],
    name: "setDestinations",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bool",
        name: "eventSendSet",
        type: "bool",
      },
    ],
    name: "setEventSend",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IEventSender__factory {
  static readonly abi = _abi;
  static createInterface(): IEventSenderInterface {
    return new utils.Interface(_abi) as IEventSenderInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IEventSender {
    return new Contract(address, _abi, signerOrProvider) as IEventSender;
  }
}
