/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ICycleRolloverTracker,
  ICycleRolloverTrackerInterface,
} from "../ICycleRolloverTracker";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "cycleIndex",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "l1Timestamp",
        type: "uint256",
      },
    ],
    name: "CycleRolloverComplete",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "cycleIndex",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "l1Timestamp",
        type: "uint256",
      },
    ],
    name: "CycleRolloverStart",
    type: "event",
  },
];

export class ICycleRolloverTracker__factory {
  static readonly abi = _abi;
  static createInterface(): ICycleRolloverTrackerInterface {
    return new utils.Interface(_abi) as ICycleRolloverTrackerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICycleRolloverTracker {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ICycleRolloverTracker;
  }
}
