/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IFraxVoteProxy,
  IFraxVoteProxyInterface,
} from "../IFraxVoteProxy";

const _abi = [
  {
    inputs: [],
    name: "operator",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IFraxVoteProxy__factory {
  static readonly abi = _abi;
  static createInterface(): IFraxVoteProxyInterface {
    return new utils.Interface(_abi) as IFraxVoteProxyInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFraxVoteProxy {
    return new Contract(address, _abi, signerOrProvider) as IFraxVoteProxy;
  }
}
