/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IFraxBooster, IFraxBoosterInterface } from "../IFraxBooster";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_pid",
        type: "uint256",
      },
    ],
    name: "createVault",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "poolRegistry",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IFraxBooster__factory {
  static readonly abi = _abi;
  static createInterface(): IFraxBoosterInterface {
    return new utils.Interface(_abi) as IFraxBoosterInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFraxBooster {
    return new Contract(address, _abi, signerOrProvider) as IFraxBooster;
  }
}
